name: CI Lint e Testes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Executar flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências de dev
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Executar flake8
        run: |
          flake8 .

  test:
    name: Executar pytest
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências (prod + dev)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Executar pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
